//! Merchants entity — now represents the Organization
//! Auth fields moved to `users` table (Role & Organization feature)

use rust_decimal::Decimal;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::None)")]
pub enum MerchantStatus {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "suspended")]
    Suspended,
    #[sea_orm(string_value = "pending_verification")]
    PendingVerification,
}

#[derive(Clone, Debug, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::None)")]
#[serde(rename_all = "snake_case")]
pub enum FeeTier {
    #[sea_orm(string_value = "standard")]
    Standard, // 0.5% (Phase 2)
    #[sea_orm(string_value = "business")]
    Business, // 0.3%
    #[sea_orm(string_value = "enterprise")]
    Enterprise, // 0.1%
}

#[derive(Clone, Debug, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::None)")]
#[serde(rename_all = "snake_case")]
pub enum FeeSource {
    /// No override set — uses global FeeConfig.fee_percentage
    #[sea_orm(string_value = "default")]
    Default,
    /// TierCalculator auto-set based on monthly volume
    #[sea_orm(string_value = "auto_tier")]
    AutoTier,
    /// Admin manually set via Admin Console
    #[sea_orm(string_value = "manual")]
    Manual,
    /// Agent set via Agent Dashboard
    #[sea_orm(string_value = "agent")]
    Agent,
}

#[derive(Clone, Debug, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::None)")]
#[serde(rename_all = "snake_case")]
pub enum MerchantType {
    /// Normal direct merchant (default)
    #[sea_orm(string_value = "direct")]
    Direct,
    /// Hidden org backing a sub-merchant (created by PSP via Admin API)
    #[sea_orm(string_value = "sub_merchant")]
    SubMerchant,
}

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "merchants")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub status: MerchantStatus,
    /// Whether this org is a direct merchant or a sub-merchant backing org
    pub merchant_type: MerchantType,
    /// Auto-generated by PostgreSQL SEQUENCE (merchant_account_index_seq)
    /// Do NOT set this manually - let the database handle it
    #[sea_orm(unique)]
    pub account_index: Option<i32>,

    // Fields moved to other tables or removed:
    // - email, password_hash, totp_secret, is_totp_enabled,
    //   token_version, backup_codes, email_verified -> users table
    // - balance_* -> MerchantChainAccounts.usdt_balance / usdc_balance
    // - xpub_encrypted, last_path_index, collection_address -> MerchantChainAccounts
    // - flat_fee, min_sweep_threshold -> Removed (Pricing in code)
    /// Custom fee percentage override. NULL = use global default.
    /// Stored as decimal fraction: 0.01 = 1%, 0.005 = 0.5%.
    #[sea_orm(column_type = "Decimal(Some((5, 4)))")]
    pub custom_fee_percentage: Option<Decimal>,
    /// Current pricing tier (auto-calculated or manually set)
    pub fee_tier: FeeTier,
    /// Who/what set the current fee: default, auto_tier, manual, agent
    pub fee_source: FeeSource,
    /// When the 30-day new-merchant promo ends
    pub first_month_ends_at: Option<DateTimeWithTimeZone>,
    /// Cached last month's gross volume (microunits)
    pub last_month_volume: i64,
    /// When the tier was last recalculated
    pub tier_updated_at: DateTimeWithTimeZone,
    /// Agent who referred this merchant (permanent, set at registration)
    pub referred_by_agent_id: Option<String>,
    /// White-label checkout: merchant logo URL stored on R2.
    /// NULL = use default IronixPay branding.
    pub logo_url: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::api_keys::Entity")]
    ApiKeys,
    #[sea_orm(has_many = "super::webhook_endpoints::Entity")]
    WebhookEndpoints,
    #[sea_orm(has_many = "super::addresses::Entity")]
    Addresses,
    #[sea_orm(has_many = "super::checkout_sessions::Entity")]
    CheckoutSessions,
    #[sea_orm(has_many = "super::billing_logs::Entity")]
    BillingLogs,
    #[sea_orm(has_many = "super::idempotency_keys::Entity")]
    IdempotencyKeys,
    #[sea_orm(has_many = "super::merchant_chain_accounts::Entity")]
    MerchantChainAccounts,
    #[sea_orm(has_many = "super::org_members::Entity")]
    OrgMembers,
    #[sea_orm(has_many = "super::sub_merchants::Entity")]
    SubMerchants,
}

impl Related<super::api_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApiKeys.def()
    }
}

impl Related<super::webhook_endpoints::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebhookEndpoints.def()
    }
}

impl Related<super::addresses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Addresses.def()
    }
}

impl Related<super::checkout_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CheckoutSessions.def()
    }
}

impl Related<super::billing_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BillingLogs.def()
    }
}

impl Related<super::idempotency_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdempotencyKeys.def()
    }
}

impl Related<super::merchant_chain_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MerchantChainAccounts.def()
    }
}

impl Related<super::org_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrgMembers.def()
    }
}

impl Related<super::sub_merchants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubMerchants.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
