import { http } from '@/utils/request';

// === Types (generated by ts-rs from backend DTOs) ===

export type { XeroConnectionResponse as XeroConnection } from '@ironix-pay/api-client/src/bindings/XeroConnectionResponse';
export type { XeroTenantDto as XeroTenant } from '@ironix-pay/api-client/src/bindings/XeroTenantDto';
export type { XeroCallbackResponse } from '@ironix-pay/api-client/src/bindings/XeroCallbackResponse';
export type { XeroAccountDto as XeroAccount } from '@ironix-pay/api-client/src/bindings/XeroAccountDto';
export type { XeroTaxRateDto as XeroTaxRate } from '@ironix-pay/api-client/src/bindings/XeroTaxRateDto';
export type { XeroSyncLogResponse as XeroSyncLog } from '@ironix-pay/api-client/src/bindings/XeroSyncLogResponse';
export type { XeroUpdateConnectionRequest } from '@ironix-pay/api-client/src/bindings/XeroUpdateConnectionRequest';
export type { XeroConnectResponse } from '@ironix-pay/api-client/src/bindings/XeroConnectResponse';
export type { XeroSelectTenantResponse } from '@ironix-pay/api-client/src/bindings/XeroSelectTenantResponse';

import type { XeroConnectionResponse } from '@ironix-pay/api-client/src/bindings/XeroConnectionResponse';
import type { XeroCallbackResponse as XeroCallbackResponseType } from '@ironix-pay/api-client/src/bindings/XeroCallbackResponse';
import type { XeroAccountDto } from '@ironix-pay/api-client/src/bindings/XeroAccountDto';
import type { XeroTaxRateDto } from '@ironix-pay/api-client/src/bindings/XeroTaxRateDto';
import type { XeroSyncLogResponse } from '@ironix-pay/api-client/src/bindings/XeroSyncLogResponse';
import type { XeroUpdateConnectionRequest } from '@ironix-pay/api-client/src/bindings/XeroUpdateConnectionRequest';
import type { XeroConnectResponse } from '@ironix-pay/api-client/src/bindings/XeroConnectResponse';
import type { XeroSelectTenantResponse } from '@ironix-pay/api-client/src/bindings/XeroSelectTenantResponse';

/** Backend PaginatedResponse<T> format */
export interface PaginatedResponse<T> {
    data: T[];
    meta: {
        total: number;
        page: number;
        page_size: number;
        total_pages: number;
    };
}

export interface XeroCapability {
    enabled: boolean;
}

// === API Functions ===

/** POST /api/internal/xero/connect — Start OAuth, returns authorize URL */
export function xeroConnect(forceReauth = false) {
    return http.post<XeroConnectResponse>('/api/internal/xero/connect', {
        force_reauth: forceReauth,
    });
}

/** POST /api/internal/xero/callback — Exchange OAuth code for tokens */
export function xeroCallback(code: string, state: string) {
    return http.post<XeroCallbackResponseType>('/api/internal/xero/callback', { code, state });
}

/** POST /api/internal/xero/select-tenant — Select tenant for multi-tenant */
export function xeroSelectTenant(tenantId: string) {
    return http.post<XeroSelectTenantResponse>('/api/internal/xero/select-tenant', { tenant_id: tenantId });
}

/** GET /api/internal/xero/capability — Whether this env has Xero integration configured */
export function getXeroCapability() {
    return http.get<XeroCapability>('/api/internal/xero/capability');
}

/** GET /api/internal/xero/connection — Get current connection status */
export function getXeroConnection() {
    return http.get<XeroConnectionResponse | null>('/api/internal/xero/connection');
}

/** PUT /api/internal/xero/connection — Update configuration */
export function updateXeroConnection(data: Partial<XeroUpdateConnectionRequest>) {
    return http.put<XeroConnectionResponse>('/api/internal/xero/connection', data);
}

/** DELETE /api/internal/xero/connection — Disconnect */
export function disconnectXero() {
    return http.delete<{ status: string }>('/api/internal/xero/connection');
}

/** GET /api/internal/xero/accounts — Fetch Xero chart of accounts */
export function getXeroAccounts() {
    return http.get<XeroAccountDto[]>('/api/internal/xero/accounts');
}

/** GET /api/internal/xero/tax-rates — Fetch available tax codes */
export function getXeroTaxRates() {
    return http.get<XeroTaxRateDto[]>('/api/internal/xero/tax-rates');
}

/** GET /api/internal/xero/sync-logs — Paginated sync history */
export function getXeroSyncLogs(page = 1, perPage = 20, sessionId?: string) {
    return http.get<PaginatedResponse<XeroSyncLogResponse>>('/api/internal/xero/sync-logs', {
        params: { page, per_page: perPage, session_id: sessionId },
    });
}

/** POST /api/internal/xero/sync-logs/:id/retry — Retry failed sync */
export function retryXeroSync(syncLogId: string) {
    return http.post<{ status: string }>(`/api/internal/xero/sync-logs/${syncLogId}/retry`);
}
