// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiErrorType =
    | "invalid_request_error"
    | "api_error"
    | "idempotency_error";

export type ApiErrorBody = {
    type: ApiErrorType;
    code: string;
    message: string;
    param?: string;
    doc_url?: string;
};

export type ApiError = {
    error: ApiErrorBody;
};
