// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * API Key creation response
 * Note: The full key is only shown once at creation time
 */
export type ApiKeyResponse = {
  id: string;
  /**
   * Full API key - shown only once!
   */
  key: string;
  /**
   * Key prefix (sk_test_ or sk_live_)
   */
  prefix: string;
  /**
   * Optional name for the API key
   */
  name: string | null;
  created_at: string;
  last_used_at: string | null;
};
