// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateApiKeyRequest = {
  /**
   * Optional name for the API key (e.g., "Production Server")
   */
  name: string | null;
  is_test: boolean;
  /**
   * 2FA code - required if 2FA is enabled
   */
  code: string | null;
};
