// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Network } from "./Network";

export type CreateSessionBody = {
  pricing_amount: string;
  pricing_currency: string;
  currency: string;
  network: Network | null;
  client_reference_id: string | null;
  /**
   * URL to redirect after successful payment (for Redirect mode)
   */
  success_url: string | null;
  /**
   * URL to redirect after payment expires or is cancelled (for Redirect mode)
   */
  cancel_url: string | null;
};
