// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Logical environment (not chain-specific)
 *
 * Used for configuration tables like `webhook_endpoints` where merchants
 * typically have only 2 URLs (dev/prod), not per-chain URLs.
 */
export type Environment = "production" | "sandbox";
