// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GasBalanceResponse = {
  balance_prod: bigint;
  balance_sandbox: bigint;
  unit: string;
};
