// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MerchantResponse } from "./MerchantResponse";

export type LoginResponse = {
  "status": "success";
  token: string;
  merchant_id: string;
  user_id: string;
  role: string;
  org_name: string;
  expires_at: number;
  merchant: MerchantResponse;
} | { "status": "requires_2fa"; temp_token: string; merchant_id: string };
