// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MerchantResponse = {
  id: string;
  name: string;
  email: string;
  user_name?: string | null;
  org_name?: string | null;
  collection_address: string | null;
  collection_address_sandbox: string | null;
  /**
   * Per-chain collection addresses: { "TRON": { "production": addr, "sandbox": addr }, "BSC": {...} }
   */
  collection_addresses?: Record<string, Record<string, string | null>>;
  is_2fa_enabled: boolean;
  status: string;
  /**
   * Production balance (human-readable decimal string, e.g. "10.5")
   */
  balance_prod: string;
  /**
   * Sandbox balance (human-readable decimal string, e.g. "10.5")
   */
  balance_sandbox: string;
  /**
   * Per-chain balances: { "TRON": { "production": "100.5" }, "BSC": { "sandbox": "50.2" } }
   */
  chain_balances?: Record<string, Record<string, string>>;
  gas_unit: string;
};
