// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MerchantStatsResponse = {
  total_volume_usdt: string;
  today_volume_usdt: string;
  total_transactions: bigint;
  total_transactions_today: bigint;
};
