// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionStatus } from "./SessionStatus";

export type SessionFilterParams = {
  status: Array<SessionStatus> | null;
  created_after: string | null;
  created_before: string | null;
  search_text: string | null;
};
