// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PricingInfo } from "./PricingInfo";
import type { SessionStatus } from "./SessionStatus";
import type { TransactionResponse } from "./TransactionResponse";

export type SessionResponse = {
  id: string;
  livemode: boolean;
  merchant_name: string;
  network: string;
  currency: string;
  amount: string;
  amount_received: string;
  pay_address: string;
  status: SessionStatus;
  client_reference_id: string | null;
  url: string;
  success_url?: string;
  cancel_url?: string;
  expires_at: string;
  created_at: string;
  fee_amount?: string;
  net_amount?: string;
  currency_contract?: string;
  detection_rpc_url?: string;
  chain_family?: string;
  pricing: PricingInfo;
  transactions: Array<TransactionResponse>;
  sub_merchant_code?: string;
  merchant_logo_url?: string;
};
