// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TotpSetupResponse = {
  secret: string;
  qr_code_uri: string;
  backup_codes: Array<string>;
};
