// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TransactionResponse = {
  tx_hash: string;
  amount: string;
  status: string;
  created_at: string;
};
