// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateProfileRequest = {
  name: string;
  /**
   * Optional: Required if 2FA is enabled
   */
  code: string | null;
};
