// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Network } from "./Network";

export type UpdateWalletAddressRequest = {
  network: Network;
  collection_address: string;
  /**
   * 2FA code is required for changing money destination
   */
  code: string | null;
};
