// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type XeroSelectTenantRequest = {
  /**
   * Tenant ID selected by the user.
   */
  tenant_id: string;
};
