// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type XeroUpdateConnectionRequest = {
  xero_account_code: string | null;
  xero_fee_account_code: string | null;
  xero_payment_account_code: string | null;
  xero_tax_type: string | null;
  auto_sync_enabled: boolean | null;
};
