// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { XeroTenantDto } from "./XeroTenantDto";

export type XeroCallbackResponse = {
  /**
   * If multiple tenants found, client must call select-tenant
   */
  tenants: Array<XeroTenantDto>;
  /**
   * Set if only one tenant (auto-selected)
   */
  connection_id: string | null;
};
