// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type XeroSyncLogsQuery = {
  page: bigint | null;
  per_page: bigint | null;
  session_id: string | null;
};
