// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type XeroConnectRequest = {
  /**
   * Optional: pre-selected environment override (defaults to merchant's current env)
   */
  environment: string | null;
  /**
   * Force re-auth even when an active connection already exists.
   */
  force_reauth: boolean | null;
};
