// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type XeroTaxRateDto = {
  tax_type: string;
  name: string;
  display_tax_rate: number;
  can_apply_to_revenue: boolean;
  status: string;
};
