// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type XeroSyncLogResponse = {
  id: string;
  session_id: string;
  xero_invoice_id: string | null;
  xero_payment_id: string | null;
  status: string;
  attempt_count: number;
  last_error: string | null;
  next_retry_at: string | null;
  created_at: string;
  updated_at: string;
};
